export {default as Home} from './Home'
export {default as Blog} from './Blog'
export {default as Album} from './Album'
export {default as Posts} from './Posts'
export {default as NewPost} from './NewPost'
export {default as Post} from './Post'
export {default as Layouts} from './Layouts'
export {default as ErrorPage} from './404'